/***************************************************************************//**
 * @file
 * @brief Root certificate definition in PEM format.
 * Autogenerated file, do not edit.
 *******************************************************************************
 * # License
 * <b>Copyright 2024 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/
#ifndef SL_BT_ROOT_CERT_H
#define SL_BT_ROOT_CERT_H

#define SL_BT_ROOT_CERT \
  "MIICWjCCAgCgAwIBAgIUIwLXUQBt6WPI4c0bu67h1rXyS4wwCgYIKoZIzj0EAwIw" \
  "gYcxCzAJBgNVBAYTAklOMQ0wCwYDVQQKDARCQVRMMQswCQYDVQQLDAJJUzEUMBIG" \
  "A1UECAwLTWFoYXJhc2h0cmExEjAQBgNVBAMMCUJBTEZvYktleTEPMA0GA1UEBwwG" \
  "QWt1cmRpMSEwHwYJKoZIhvcNAQkBFhJzdXBwb3J0QHNpbGFicy5jb20wHhcNMjUw" \
  "OTA0MTEzODIyWhcNMjYwOTA0MTEzODIyWjCBhzELMAkGA1UEBhMCSU4xDTALBgNV" \
  "BAoMBEJBVEwxCzAJBgNVBAsMAklTMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTESMBAG" \
  "A1UEAwwJQkFMRm9iS2V5MQ8wDQYDVQQHDAZBa3VyZGkxITAfBgkqhkiG9w0BCQEW" \
  "EnN1cHBvcnRAc2lsYWJzLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABE+b" \
  "Vg2BR9734k8nW6U5r3pUTp/9bWF1QNyomJ0aUx2fnuPW6nvtx6OzmxuKRQUFepmI" \
  "+swlQpvyqB0ZvOFbPFOjSDBGMB0GA1UdDgQWBBSCdLNpVb8aS8aBFtsxkBWNWET+" \
  "3zAPBgNVHRMBAf8EBTADAQH/MBQGA1UdIAEB/wQKMAgwBgYEVR0gADAKBggqhkjO" \
  "PQQDAgNIADBFAiAuFdTpuEnYyY+MeMai1oeTVg8PyisUKS2Xbewl0U2ZXwIhAM3+" \
  "1jwY+9gFKiTIXdOt5tk+SW42HeDnj6et7nx8LQrs"

#endif // SL_BT_ROOT_CERT_H