/**
 * @file          SETU_Uuid.h
 * @brief         Default 128-bit UUIDs of the SETU GATT service.
 *
 *                The Server hosts the service; the Client discovers it with
 *                these UUIDs unless SETUCliCfg_T overrides them. UUIDs follow
 *                the GATT Configurator scheme: the project-wide 96-bit base
 *                from BaseUUIDs.h plus this library's first 32 bits
 *                | 8-bit Domain | 8-bit Service ID | 16-bit Char ID |.
 *
 *                  Service  B1C00000-<base>
 *                  DATA     B1C00001-<base>  Write Without Response: client -> server
 *                  CTRL     B1C00002-<base>  Notify: server -> client
 *                  Caps     B1C00003-<base>  Read: SETUCaps_T
 *
 *                BaseUUIDs.h (generated by the GATT Configurator) must be on
 *                the include path.
 *
 * @date          24/09/2026
 * @author        Shivam Chudasama
 * @copyright     Shivam Chudasama
 * @license       MIT
 */

/* SPDX-License-Identifier: MIT */

#ifndef _SETU_UUID_H
#define _SETU_UUID_H

/******************************************************************************/
/*                                                                            */
/*                                  INCLUDES                                  */
/*                                                                            */
/******************************************************************************/
#include <stdint.h>
#include <zephyr/bluetooth/uuid.h>
#include "BaseUUIDs.h"

/******************************************************************************/
/*                                                                            */
/*                                  DEFINES                                   */
/*                                                                            */
/******************************************************************************/
// Domain
#ifndef PART_UUID_DOMAIN_SETU
/**
 * @def           PART_UUID_DOMAIN_SETU
 * @brief         SETU domain.
 */
#define PART_UUID_DOMAIN_SETU            (0xB1)
#endif // PART_UUID_DOMAIN_SETU

// Service UUID
#ifndef PART_UUID_SERVICE_SETU
/**
 * @def           PART_UUID_SERVICE_SETU
 * @brief         SETU service.
 */
#define PART_UUID_SERVICE_SETU           (0xC0)
#endif // PART_UUID_SERVICE_SETU

/**
 * @def           SETU_SERVICE_UUID_FIRST_PART_32BIT
 * @brief         First part of SETU service UUID (32-bits).
 */
#define SETU_SERVICE_UUID_FIRST_PART_32BIT \
                                             (UUID_FIRST_PART_32BIT( \
                                                PART_UUID_DOMAIN_SETU, \
                                                PART_UUID_SERVICE_SETU, \
                                                0x0000))

/**
 * @def           BT_UUID_SETU_SVC_VAL
 * @brief         128-bit value encoding for SETU service UUID.
 */
#define BT_UUID_SETU_SVC_VAL                  BT_UUID_128_ENCODE( \
                                                SETU_SERVICE_UUID_FIRST_PART_32BIT, \
                                                BASE_UUID_SECOND_PART_16BIT, \
                                                BASE_UUID_THIRD_PART_16BIT, \
                                                BASE_UUID_FOURTH_PART_16BIT, \
                                                BASE_UUID_FIFTH_PART_48BIT)

/**
 * @def           BT_UUID_SETU_SVC
 * @brief         Creating UUID structure pointer (const struct bt_uuid *) for
 *                SETU service.
 */
#define BT_UUID_SETU_SVC                      BT_UUID_DECLARE_128(BT_UUID_SETU_SVC_VAL)

// Characteristic UUID. SETU-prefixed so they cannot clash with a generated
// service that also has a 'DATA' / 'CTRL' characteristic.
/**
 * @def           PART_UUID_CHAR_SETU_DATA
 * @brief         UUID 'DATA' characteristic (client -> server).
 */
#define PART_UUID_CHAR_SETU_DATA              (0x0001)

/**
 * @def           SETU_DATA_CHAR_UUID_FIRST_PART_32BIT
 * @brief         First part of 'DATA' characteristic UUID (32-bits).
 */
#define SETU_DATA_CHAR_UUID_FIRST_PART_32BIT  (UUID_FIRST_PART_32BIT( \
                                                PART_UUID_DOMAIN_SETU, \
                                                PART_UUID_SERVICE_SETU, \
                                                PART_UUID_CHAR_SETU_DATA))

/**
 * @def           BT_UUID_SETU_DATA_VAL
 * @brief         128-bit value encoding for 'DATA' characteristic UUID.
 */
#define BT_UUID_SETU_DATA_VAL                 BT_UUID_128_ENCODE( \
                                                SETU_DATA_CHAR_UUID_FIRST_PART_32BIT, \
                                                BASE_UUID_SECOND_PART_16BIT, \
                                                BASE_UUID_THIRD_PART_16BIT, \
                                                BASE_UUID_FOURTH_PART_16BIT, \
                                                BASE_UUID_FIFTH_PART_48BIT)

/**
 * @def           BT_UUID_SETU_DATA
 * @brief         Creating UUID structure pointer (const struct bt_uuid *) for
 *                'DATA' characteristic.
 */
#define BT_UUID_SETU_DATA                     BT_UUID_DECLARE_128(BT_UUID_SETU_DATA_VAL)

/**
 * @def           PART_UUID_CHAR_SETU_CTRL
 * @brief         UUID 'CTRL' characteristic (server -> client).
 */
#define PART_UUID_CHAR_SETU_CTRL              (0x0002)

/**
 * @def           SETU_CTRL_CHAR_UUID_FIRST_PART_32BIT
 * @brief         First part of 'CTRL' characteristic UUID (32-bits).
 */
#define SETU_CTRL_CHAR_UUID_FIRST_PART_32BIT  (UUID_FIRST_PART_32BIT( \
                                                PART_UUID_DOMAIN_SETU, \
                                                PART_UUID_SERVICE_SETU, \
                                                PART_UUID_CHAR_SETU_CTRL))

/**
 * @def           BT_UUID_SETU_CTRL_VAL
 * @brief         128-bit value encoding for 'CTRL' characteristic UUID.
 */
#define BT_UUID_SETU_CTRL_VAL                 BT_UUID_128_ENCODE( \
                                                SETU_CTRL_CHAR_UUID_FIRST_PART_32BIT, \
                                                BASE_UUID_SECOND_PART_16BIT, \
                                                BASE_UUID_THIRD_PART_16BIT, \
                                                BASE_UUID_FOURTH_PART_16BIT, \
                                                BASE_UUID_FIFTH_PART_48BIT)

/**
 * @def           BT_UUID_SETU_CTRL
 * @brief         Creating UUID structure pointer (const struct bt_uuid *) for
 *                'CTRL' characteristic.
 */
#define BT_UUID_SETU_CTRL                     BT_UUID_DECLARE_128(BT_UUID_SETU_CTRL_VAL)

/**
 * @def           PART_UUID_CHAR_SETU_CAPS
 * @brief         UUID 'Caps' characteristic (SETUCaps_T, read).
 */
#define PART_UUID_CHAR_SETU_CAPS              (0x0003)

/**
 * @def           SETU_CAPS_CHAR_UUID_FIRST_PART_32BIT
 * @brief         First part of 'Caps' characteristic UUID (32-bits).
 */
#define SETU_CAPS_CHAR_UUID_FIRST_PART_32BIT  (UUID_FIRST_PART_32BIT( \
                                                PART_UUID_DOMAIN_SETU, \
                                                PART_UUID_SERVICE_SETU, \
                                                PART_UUID_CHAR_SETU_CAPS))

/**
 * @def           BT_UUID_SETU_CAPS_VAL
 * @brief         128-bit value encoding for 'Caps' characteristic UUID.
 */
#define BT_UUID_SETU_CAPS_VAL                 BT_UUID_128_ENCODE( \
                                                SETU_CAPS_CHAR_UUID_FIRST_PART_32BIT, \
                                                BASE_UUID_SECOND_PART_16BIT, \
                                                BASE_UUID_THIRD_PART_16BIT, \
                                                BASE_UUID_FOURTH_PART_16BIT, \
                                                BASE_UUID_FIFTH_PART_48BIT)

/**
 * @def           BT_UUID_SETU_CAPS
 * @brief         Creating UUID structure pointer (const struct bt_uuid *) for
 *                'Caps' characteristic.
 */
#define BT_UUID_SETU_CAPS                     BT_UUID_DECLARE_128(BT_UUID_SETU_CAPS_VAL)

/******************************************************************************/
/*                                                                            */
/*                                   ENUMS                                    */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/*                                                                            */
/*                                 STRUCTURES                                 */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/*                                                                            */
/*                                   UNIONS                                   */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/*                                                                            */
/*                              EXTERN VARIABLES                              */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/*                                                                            */
/*                              EXTERN FUNCTIONS                              */
/*                                                                            */
/******************************************************************************/

#endif // _SETU_UUID_H
