#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the certificates for the device's X.509 verification test
(_TEST/unit/DeviceCert/test_devicecert_verify.c) as a C header.

    python gen_cert_vectors.py <out.h>

Built by the CMake test project on every fresh build, with new keys each time,
from the PC tool's own code, so the device is tested against exactly what the
PC sends:
  - blehost.pki.authority.CertificateAuthority makes the CA and signs the
    device's CSR (the good CA and device certificate);
  - blehost.pki.negative.negative_cases() makes every certificate the device
    must reject, each with the RESULT status it must answer.

The "device" is a P-256 key made here: its private scalar goes into the
header so the test can import it into PSA as the persistent device key
(CSR_DEVICE_SIGNING_KEY_ID), and its CSR (subject as the device builds it:
C, ST, L, O, OU, CN, KeyUsage keyAgreement) stands in for gst_CSRData.
A second device ("remote", phase-2 pairing) and a second CA are included too.

Needs cryptography (_TEST/requirements-test.txt).
"""

import os
import sys
import tempfile

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import NameOID

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "_TOOLS", "BleHostGUI"))

from blehost.pki import negative  # noqa: E402
from blehost.pki.authority import CertificateAuthority  # noqa: E402


def _csr(key, cn: str) -> bytes:
    name = x509.Name([
        x509.NameAttribute(NameOID.COUNTRY_NAME, "IN"),
        x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, "Maharashtra"),
        x509.NameAttribute(NameOID.LOCALITY_NAME, "Pune"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Test Organisation"),
        x509.NameAttribute(NameOID.ORGANIZATIONAL_UNIT_NAME, "Test Unit"),
        x509.NameAttribute(NameOID.COMMON_NAME, cn),
    ])
    ku = x509.KeyUsage(digital_signature=True, content_commitment=False, key_encipherment=False,
                       data_encipherment=False, key_agreement=True, key_cert_sign=False,
                       crl_sign=False, encipher_only=False, decipher_only=False)
    csr = (x509.CertificateSigningRequestBuilder().subject_name(name)
           .add_extension(ku, critical=True).sign(key, hashes.SHA256()))
    return csr.public_bytes(serialization.Encoding.DER)


def _point(key) -> bytes:
    return key.public_key().public_bytes(serialization.Encoding.X962,
                                         serialization.PublicFormat.UncompressedPoint)


def _array(name: str, data: bytes) -> str:
    lines = [",".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    return (f"static const uint8_t {name}[] = {{\n   " + ",\n   ".join(lines) + "\n};\n"
            f"#define {name.upper()}_LEN ((size_t){len(data)}U)\n")


def generate() -> str:
    dev_key = ec.generate_private_key(ec.SECP256R1())
    remote_key = ec.generate_private_key(ec.SECP256R1())
    dev_csr = _csr(dev_key, "00112233-4455-5677-8899-aabbccddeeff")
    remote_csr = _csr(remote_key, "ffeeddcc-bbaa-5988-7766-554433221100")

    with tempfile.TemporaryDirectory() as tmp:
        ca = CertificateAuthority.create(os.path.join(tmp, "ca"), {"CN": "Test CA", "O": "Test"})
        ca2 = CertificateAuthority.create(os.path.join(tmp, "ca2"), {"CN": "Second CA"})
        dev_cert = ca.sign_csr(dev_csr).der
        dev_cert_ca2 = ca2.sign_csr(dev_csr).der
        remote_cert = ca.sign_csr(remote_csr).der
        cases = negative.negative_cases(ca, dev_csr)
        ca_der, ca2_der = ca.cert_der, ca2.cert_der

    out = ["/* Generated by _TEST/tools/gen_cert_vectors.py: do not edit. */",
           "#ifndef CERT_VECTORS_H", "#define CERT_VECTORS_H", "#include <stdint.h>",
           "#include <stddef.h>", ""]
    scalar = dev_key.private_numbers().private_value.to_bytes(32, "big")
    for name, data in (("gu8ar_certCa", ca_der), ("gu8ar_certCa2", ca2_der),
                       ("gu8ar_certDevKey", scalar), ("gu8ar_certDevPub", _point(dev_key)),
                       ("gu8ar_certDevCsr", dev_csr), ("gu8ar_certDev", dev_cert),
                       ("gu8ar_certDevByCa2", dev_cert_ca2), ("gu8ar_certRemote", remote_cert),
                       ("gu8ar_certRemotePub", _point(remote_key))):
        out.append(_array(name, data))
    for i, c in enumerate(cases):
        out.append(_array(f"gu8ar_certCase{i}", c.der))
    out.append("typedef struct { const char *cpt_name; uint8_t u8_appType; const uint8_t *u8pt_der;\n"
               "   size_t t_len; uint8_t u8_expected; } CertCase_T;")
    out.append(f"#define CERT_APP_CA ((uint8_t)0x{negative.CA_CERT:02x}U)")
    out.append(f"#define CERT_APP_DEV ((uint8_t)0x{negative.DEV_CERT:02x}U)")
    out.append("static const CertCase_T gstar_certCases[] = {")
    for i, c in enumerate(cases):
        out.append(f'   {{ "{c.name}", 0x{c.app_type:02x}U, gu8ar_certCase{i}, '
                   f"GU8AR_CERTCASE{i}_LEN, 0x{c.expected:02x}U }},")
    out.append("};")
    out.append(f"#define CERT_CASE_CNT ((uint32_t){len(cases)}U)")
    out.append("#endif /* CERT_VECTORS_H */")
    return "\n".join(out) + "\n"


def main() -> int:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    text = generate()
    os.makedirs(os.path.dirname(os.path.abspath(sys.argv[1])), exist_ok=True)
    with open(sys.argv[1], "w", newline="\n") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
