#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate wire_vectors.h for the C tests from _TEST/vectors/wire.json.

The hex-upload segment bytes are read from the repo's test .hex file with a
minimal Intel HEX reader of its own, deliberately independent of
bulkxfer_client.parse_ihex(), so the C end-to-end test does not inherit a bug
from the code the Python tests check.

    python gen_vectors.py <wire.json> <repo root> <out.h>
"""

import json
import os
import sys

KINDS = ("START", "DATA", "ACK", "NACK", "END", "ABORT", "SHORT")
FIELDS = {                                            # order of VEC_F[] per kind
    "START": ("xid", "app_type", "total_len", "chunk", "window", "crc32"),
    "DATA": ("xid", "seq"),
    "ACK": ("xid", "seq", "window"),
    "NACK": ("xid", "seq", "reason"),
    "END": ("xid", "status"),
    "ABORT": ("xid", "reason", "dir"),
    "SHORT": ("app_type",),
}


def read_ihex(path: str) -> dict:
    """Intel HEX -> {address: byte}. Types 00, 01, 02, 04; 03/05 ignored."""
    mem, upper, seg_wrap = {}, 0, False
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = bytes.fromhex(line[1:])
            assert line[0] == ":" and len(rec) == rec[0] + 5 and sum(rec) & 0xFF == 0, line
            addr, rtype, data = (rec[1] << 8) | rec[2], rec[3], rec[4:-1]
            if rtype == 0:
                for i, b in enumerate(data):
                    off = addr + i
                    mem[upper + ((off & 0xFFFF) if seg_wrap else off)] = b
            elif rtype == 1:
                break
            elif rtype == 2:                          # segment: offsets wrap at 64 KiB
                upper, seg_wrap = int.from_bytes(data, "big") << 4, True
            elif rtype == 4:
                upper, seg_wrap = int.from_bytes(data, "big") << 16, False
    return mem


def c_bytes(b: bytes, indent: str = "      ") -> str:
    if not b:
        return "0"
    rows = [", ".join(f"0x{x:02x}" for x in b[i:i + 12]) for i in range(0, len(b), 12)]
    return (",\n" + indent).join(rows)


def main(json_path: str, root: str, out_path: str) -> None:
    with open(json_path) as f:
        v = json.load(f)

    o = []
    o.append("/* Generated by _TEST/tools/gen_vectors.py from _TEST/vectors/wire.json. Do not edit. */")
    o.append("#ifndef WIRE_VECTORS_H\n#define WIRE_VECTORS_H\n#include <stdint.h>\n")
    o.append(f"#define VEC_PROTOCOL_VERSION ({v['protocol_version']}U)")
    o.append(f"#define VEC_MAX_FRAME_LEN    ({v['max_frame_len']}U)")
    o.append(f"#define VEC_WINDOW           ({v['window']}U)")
    o.append(f"#define VEC_APP_TYPE_MAX     ({v['app_type_max']}U)")
    for group, prefix in (("frame_types", "VEC_T_"), ("status", "VEC_ST_"),
                          ("abort_dir", "VEC_DIR_"), ("hex_app_types", "VEC_APP_")):
        for name, val in v[group].items():
            o.append(f"#define {prefix}{name} ({val}U)")

    o.append("\ntypedef enum { " + ", ".join(f"eVK_{k}" for k in KINDS) + " } VecKind_E;")
    o.append("typedef struct\n{\n   const char *cpt_name;\n   VecKind_E e_kind;\n"
             "   uint32_t u32ar_f[6];          /* fields, order per kind in gen_vectors.py */\n"
             "   uint8_t u8ar_data[16];        /* DATA bytes / SHORT payload            */\n"
             "   uint8_t u8_dataLen;\n   uint8_t u8ar_wire[20];\n   uint8_t u8_wireLen;\n} WireVector_T;\n")
    o.append("static const WireVector_T gstar_vecFrames[] =\n{")
    for fr in v["frames"]:
        kind = fr["kind"]
        fields = ", ".join(f"{fr[k]}U" for k in FIELDS[kind]) or "0"
        data = bytes.fromhex(fr.get("data", fr.get("payload", "")))
        wire = bytes.fromhex(fr["hex"])
        o.append(f"   {{ \"{fr['name']}\", eVK_{kind}, {{ {fields} }},\n"
                 f"      {{ {c_bytes(data)} }}, {len(data)}U,\n"
                 f"      {{ {c_bytes(wire)} }}, {len(wire)}U }},")
    o.append("};\n")

    o.append("typedef struct\n{\n   const char *cpt_name;\n   uint8_t u8_appType;\n   uint8_t u8_status;\n"
             "   uint32_t u32_address;\n   uint32_t u32_length;\n   uint8_t u8ar_wire[11];\n} ReportVector_T;\n")
    o.append("static const ReportVector_T gstar_vecReports[] =\n{")
    for r in v["reports"]:
        wire = bytes.fromhex(r["hex"])
        o.append(f"   {{ \"{r['name']}\", {r['app_type']}U, {r['status']}U, {r['address']}UL, {r['length']}UL,\n"
                 f"      {{ {c_bytes(wire)} }} }},")
    o.append("};\n")

    o.append(f"static const uint8_t gu8ar_vecCaps[] = {{ {c_bytes(bytes.fromhex(v['caps']['hex']))} }};\n")

    hu = v["hex_upload"]
    mem = read_ihex(os.path.join(root, hu["file"]))
    seg = hu["segments"][0]
    data = bytes(mem[a] for a in range(seg["address"], seg["address"] + seg["length"]))
    start = next(i for i, fr in enumerate(v["frames"]) if fr["name"] == hu["start_frame"])
    o.append(f"/* First segment of {hu['file']} */")
    o.append(f"#define VEC_HEX_SEG_ADDR     ({seg['address']}UL)")
    o.append(f"#define VEC_HEX_SEG_LEN      ({seg['length']}UL)")
    o.append(f"#define VEC_HEX_START_IDX    ({start}U)")
    o.append(f"#define VEC_HEX_SEG_LINE     \"{hu['seg_line']}\"")
    o.append(f"static const uint8_t gu8ar_vecHexSeg[VEC_HEX_SEG_LEN] =\n{{\n   {c_bytes(data, '   ')}\n}};\n")
    o.append("#endif /* WIRE_VECTORS_H */\n")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(o))


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(*sys.argv[1:])
