# Extra configuration for flash spi interface. This file adds additional properties
# to the flash configuration, and is included by flash.conf when the SPI flash
# interface is selected.
# The properties defined here are used by the flash manager to determine how to
# interact with the flash device, and by the flash layout to determine how to
# layout the flash memory.
# These properties overwrite any existing project configuration in prj.conf, so
# they should be used with care.

# Enable SPI NOR Flash Support.
CONFIG_SPI_NOR=y

# Enable the flash manager to use the SPI flash interface.
CONFIG_FSMGR_FLASH_IF_SPI=y

# Set the page size for the flash layout to 4096 bytes.
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
