# Extra configuration for flash sqspi interface. This file adds additional properties
# to the flash configuration, and is included by flash.conf when the sQSPI flash
# interface is selected.
# The properties defined here are used by the flash manager to determine how to
# interact with the flash device, and by the flash layout to determine how to
# layout the flash memory.
# These properties overwrite any existing project configuration in prj.conf, so
# they should be used with care.

# Enable sQSPI NOR Flash Support.
CONFIG_MSPI=y

# Enable the flash manager to use the sQSPI flash interface.
CONFIG_FSMGR_FLASH_IF_SQSPI=y

# Set the page size for the flash layout to 4096 bytes.
CONFIG_FLASH_MSPI_NOR_LAYOUT_PAGE_SIZE=4096

# Enable the sQSPI driver for Nordic Semiconductor devices.
CONFIG_MSPI_NRF_SQSPI=y

# Override the external driver check for power management to allow the sQSPI
# driver to be used with power management enabled.
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y
